[package]
name = "Tickeys"
version = "0.3.6"
authors = ["应元东 <ying@yingDev.com>"]
build = "build.rs"


[dependencies]
libc = "0.1.8"
glutin_cocoa = "0.1.6"
time = "0.1.25"
objc = "0.1.5"
hyper = "0.6.3"
block = "*"
rustc-serialize = "0.3.15"
openal-rs = "0.1.1"


